### ISSUE TITLE
Characterization, De-challenge/re-challenge: duplicated results in data table

### ISSUE THREAD

**Issue by nhall6** [OHDSI/OhdsiShinyModules#100]
In standardization branch Strategus dashboard we can see a bug where the same/duplicate de-challenge/re-challenge results are being presented for a given T/O/DB combination

**Comment by jreps** [comment]
I added a distinct to the sql used to extract the data to ensure rows are unique

**Comment by jreps** [comment]
fixed in https://github.com/OHDSI/OhdsiShinyModules/tree/issue_100
