### ISSUE TITLE
Meta: Bug in SCCS plot (details below)

### ISSUE THREAD

**Issue by nhall6** [OHDSI/OhdsiShinyModules#110]
From Mitch : "This could well be user error but for one request, we had only one SCCS analyses that passed diagnostics and multiple CohortMethod analyses that passed diagnostics. When we go to the "Meta" module tab and click the sub-lists for:
    o	"SCCS Plot" we get an error message reading: "ERROR: An error has occurred. Check your logs or contact the app author for clarification."
    o	"SCCS Table" the table is empty
    o	Not necessarily saying a single database's results should be sent to the meta-analysis tab, but it may be confusing if people think the reason results are not displaying is due to an error rather than "no results to display"."

**Comment by jreps** [comment]
We have separate meta tabs for CM and SCCS now since the cohorts are often different.  This change will have fixed this issue.
