### ISSUE TITLE
General: Allow resizing of columns in all tables (user click and drag resizing in the UI)

### ISSUE THREAD

**Issue by nhall6** [OHDSI/OhdsiShinyModules#113]

**Comment by gowthamrao** [comment]
@nhall6 fyi  - here is an example of a function that is used in cohort diagnostics to make it easier to turn on/off functions using reactable https://github.com/OHDSI/OhdsiShinyModules/blob/745a08d7f91f39d6fa86e83154a316a60f0400bf/R/cohort-diagnostics-shared.R#L196

A function like that may allow for easier management of table output

**Comment by nhall6** [comment]
This functionality has now been added
