### ISSUE TITLE
Estimation, CohortMethod, Results: Improvements

### ISSUE THREAD

**Issue by nhall6** [OHDSI/OhdsiShinyModules#114]
-	Create section for options to select before generate:  Target, Comparator, Outcome, Database, Analysis
-	Show /hide columns -  default:  only show Cal HR, Cal LB, Cal UB, Cal p

-	Results/Power:
   o	Need to download results, is it two tables/csv for Table 1a and Table 1b?   (desirable to be able to download across databases/analyses, not only in drilldown to 1 DB/1 analysis)

-	Results/Attrition:
   o	Some text overlaps box outline

-	Population characteristics:
   o	Show raw table (not just ‘pretty’) with target/comparator std diff before and after PS adjustment  

-	Propensity model:
   o	Sort beta by value  (current bug:  doesn’t sort as number correctly), need to cast as sortable value
   o	Consider column with abs(beta) to sort on covariate with largest coefficient
   o	Add column for covariate prevalence for T and C pre-adjustment (so that you can determine feature importance) ….same values in Population Characteristics

-	Propensity score:  
   o	overlay equipoise statistic
   o	Red/blue legend;   need to truncate cohort name to allow for both categories to be shown

-	Covariate balance:   
   o	overlay maxSDM

-	Systematic error:  
   o	overlay EASE
   o	– description of attrition from negative control list provided to negative controls with estimates
   o	When downloading graph, has some identifier for database/analysis (could be title on the plot or name of the image itself)

-	ASE003 doesn’t show Kaplan-Meier plots (was on ASE001)
   o	Aesthetics to improve in KM plot:
      	Long cohort name label in Life table distorts the graph

**Comment by jreps** [comment]
The KM issue has been resolved previously and the power table now has a download option (3rd and last bullets).

**Comment by jreps** [comment]
Nate - can you check which of these issues remain?  I think most are resolved and this could be closed.  In future, it may be easier to post each issue separately as that makes it easier to keep track.
