### ISSUE TITLE
General: Freeze column headings when doing a vertical scroll 

### ISSUE THREAD

**Issue by nhall6** [OHDSI/OhdsiShinyModules#115]
Similar to Freeze Panes in excel, want to freeze column headings if tables are long (maybe past X length?)

**Comment by jreps** [comment]
Do we still want this?  I think most tables seem good now

**Comment by nhall6** [comment]
> Do we still want this? I think most tables seem good now

@jreps I was looking at this issue as well and contemplating. Standard reactable functionality now supports left and right-side table freezing, but not top or bottom freezing. I am thinking this is not a priority for us to custom code, especially since we have already shortened the vertical length of tables and plots. I think we can close it - what do you think?
