### ISSUE TITLE
Meta: Improvements

### ISSUE THREAD

**Issue by nhall6** [OHDSI/OhdsiShinyModules#117]
-	Cohort Method Plot:
   o	Order graph so that meta-analysis is always on the bottom (other databases alphabetized)
   o	Default: Bayesian random-effect (fault handling:  it’s possible that not all meta-analyses are generated)

-	SCCS Plot:
   o	Label of analysis/TAR can get long and unreadable
   o	Plot is only displaying meta-analysis estimates, not the source-specific estimates

-	SCCS Table:
   o	Table only contains meta-analytic estimates, needs to also show source-specific estimates to be consistent with Cohort Method Table

**Comment by jreps** [comment]
@nhall6  I think many of these have already been addressed (adding this into OKR1b as it should be a quick fix)

**Comment by jreps** [comment]
These issues seem to already be fixed
