### ISSUE TITLE
Characterization output not displayed - No concept set id chosen

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/OhdsiShinyModules#120]
I see a message - No concept set id chosen

to reproduce go to https://data.ohdsi.org/PhenotypeLibrary/ and repeat the selections in screen shot

![image](https://user-images.githubusercontent.com/13936600/202603708-0f37f7e7-29ba-4e4e-8514-c09e9ac3061b.png)

**Comment by azimov** [comment]
possibly already resolved in latest version,  needs confirmation

**Comment by jreps** [comment]
I tested the settings on new app and do not get that error, so closing this.
