### ISSUE TITLE
Database drop down have a gray shading on top of them

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/OhdsiShinyModules#123]
![image](https://user-images.githubusercontent.com/13936600/193073595-47278925-5d83-4dcc-a06d-68c67aa252e6.png)

this is new, it wasnt there before

![image](https://user-images.githubusercontent.com/13936600/193073873-91592c08-0819-4b0a-aef0-b92546bfc5d2.png)

**Comment by jreps** [comment]
@azimov  - has this been fixed in the latest app?
