### ISSUE TITLE
Incidence Rate tab:   bugs and suggested enhancements

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/OhdsiShinyModules#125]
1. ENHANCEMENT: Remove all reactive dropdown/checkboxes.   Instead, make user pick the desired parameters and then click 'Generate plot'.    Currently, with the reactives, each edit to age group, calendar year filter results in refresh, and can queue up and take awhile.

2. BUG;  Download button to the right of the user selections does not work.  Not sure if it should produce jpg of graph or tabular output, but currently it generates dowload.html of page that is nonsense.
 
![image](https://user-images.githubusercontent.com/731930/191136604-487457e9-f3d5-4923-aa17-e25071e9c721.png)

![image](https://user-images.githubusercontent.com/731930/191136653-8b6016e2-02db-4b93-b7c8-2338855663b3.png)

3.  POTENTIAL BUG?    The hoverover/tooltip show Incidence Proportion as 100% for all cohorts.   I would presume this should be % of persons in database that belong to cohort, so definitely isn't 100%.   But, it seems like it may be % of persons in cohort who belong to a specific age/sex strata?   I don't think thats the desired/expected behavior, but if it is, then should be clearly documented somewhere to avoid confusion.
![image](https://user-images.githubusercontent.com/731930/191136934-aba1539d-c607-49a3-8d07-a30296f7cfcf.png)

4.  ENHANCEMENT: Currently, cohorts are labeled by Cohort field, with a 'lookup' above the graph.   It'd be desirable to directly apply the cohort name on the graph (ex. as column heading across trellis.).

**Comment by jreps** [comment]
These issues appear to be fixed in current code so closing
