### ISSUE TITLE
changing database selection did not update the attrition table data

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/OhdsiShinyModules#153]
In this case I selected a different database from the top drop down but the attrition table data did not update.  Screenshot attached.

<img width="1633" alt="image" src="https://user-images.githubusercontent.com/6586384/236239369-9fe80c70-b323-4b55-9853-4f15e209998d.png">

While this might have been due to a server hang, it would be helpful if changing a selection would remove the previous results and show a loading indicator until the loading is complete, or use the same 'Generate' button paradigm of other reports.

**Comment by nhall6** [comment]
fixed in develop
