### ISSUE TITLE
Handle large results tables more efficiently - Characterization module does not fully load

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/OhdsiShinyModules#154]
<img width="929" alt="image" src="https://user-images.githubusercontent.com/731930/236239622-12a8dfdd-01d2-408d-8418-f19bc6465149.png">

When clicking on Characterization module, Target Viewer, it should require selection of Target cohort, but the chooser didn't load and instead the refresh is stuck.

**Comment by jreps** [comment]
Edit to FE seems to have fixed this issue
