### ISSUE TITLE
Dechallenge Rechallenge Fails Plot is empty

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/OhdsiShinyModules#156]
When I go to 

Characterization -> Dechallenge Rechallenge -> Plot Fails 

For a database with dechallenge failures the plot is empty and does not show the horizontal lines for the persons who fail.

![image](https://user-images.githubusercontent.com/12911960/236242875-4eaccb2f-983e-4144-9c7f-6a7c03968b22.png)

**Comment by jreps** [comment]
If user clicks on button when no fails how about a message saying "No fails to show" and the plot action does not occur?

**Comment by clairblacketer** [comment]
I like that, it would make it more clear that there are no fails

**Comment by jreps** [comment]
fixed in https://github.com/OHDSI/OhdsiShinyModules/tree/issue_156
