### ISSUE TITLE
Characterization --> Incidence Rate --> Table Sort TAR

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/OhdsiShinyModules#159]
1. On the "Characterization" screen, the "Incidence Rate" tab
2. In the results Table, if you look at the TAR option, the options are out of order

![image](https://user-images.githubusercontent.com/6305439/236246798-6ac3512b-04d6-42d3-90c8-a83036787a78.png)

**Comment by nhall6** [comment]
added code to support this. TAR filter should now sort in ascending order based on end number of days in TAR. fixed in issue_159 branch
