### ISSUE TITLE
CohortDiagnostics / Index Event Breakdown is not displaying despite having been run

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/OhdsiShinyModules#161]
<img width="914" alt="image" src="https://user-images.githubusercontent.com/731930/236248599-6c766478-6af8-4b9a-ac05-d7db1e9c38d1.png">

Ambulatory EHR has index event breakdown run, but there is no way to access results.

**Comment by jreps** [comment]
I can't reproduce this in the new app.
