### ISSUE TITLE
Misleading results in outcome stratified plot

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/OhdsiShinyModules#163]
When I choose a target and outcome in the outcome stratified report I get these results for IBM MDCD and Optum EHR:

![image](https://user-images.githubusercontent.com/12911960/236249988-ece8ae06-7584-43c5-ab76-f5212eb9d8e4.png)

I interpret this to say "42.75% of patients with a target of first exposure to a Janssen COVID vaccine with an outcome of urinary bleed events are Male" 

However, when I look at this same target and outcome on the incident rate report, regardless of which way I calculate (given the other bug with multiple rows per database and gender) the percentage of patients in the target cohort with the outcome who are male are only about 25-30%

**Comment by jreps** [comment]
I guess we could hide the outcome display if two targets are selected or this may be solved by giving proper column names such as "Target (first exposure): [EPI_895] Persons with first COVID vac..."?

**Comment by clairblacketer** [comment]
Yeah I think what confuses me here is that the report is labeled "Outcome stratified" but the results look like they are based on the target cohort.

**Comment by jreps** [comment]
this module has been updated due to having to restructure the outcome stratified results to scale for many T and Os.  You can no longer compare across databases and the columns names have been updated to T with O and T without O to improve clarity.
