### ISSUE TITLE
Database label not displayed when viewing cohort counts in CD cohort defn

### ISSUE THREAD

**Issue by jamieweaver** [OHDSI/OhdsiShinyModules#164]
in CohortDiagnostics, select cohort definitions -> select a cohort -> select cohort count tab, a person and event count per database is displated, but only the databaseId numeric value is displayed rather than the label
![image](https://user-images.githubusercontent.com/7608016/236251350-78fc9532-d222-499f-971c-e23eab9baeb2.png)

**Comment by jreps** [comment]
This is now fixed
