### ISSUE TITLE
Cohort Overlap Plot View: Database label overlap

### ISSUE THREAD

**Issue by clairblacketer** [OHDSI/OhdsiShinyModules#167]
I hope this is not a duplicate but when viewing the cohort overlap plot the names of the databases overlap each other and it is difficult to discern which value is which.

![image](https://user-images.githubusercontent.com/12911960/236257332-74bbb2c2-ec77-4642-bcf9-9e9ce90adc9a.png)

**Comment by jreps** [comment]
I've added code to add a new line every N characters (and set it to 25 for now)
