### ISSUE TITLE
Prediction: clicking model icon launches json code

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/OhdsiShinyModules#169]
On Prediction menu item when clicking model view icon the result is json code. The user expected to see a list of the model covariates and the coefficient values. 
![image](https://user-images.githubusercontent.com/11822115/236258187-4f639edd-900c-4a71-a5fb-c8172cc6ec68.png)

**Comment by jreps** [comment]
This is a view for the model settings.  I'll change the name of the button to make this clear.
