### ISSUE TITLE
Estimation --> Cohort Method Evidence Explorer --> Round Diagnostic Numbers

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/OhdsiShinyModules#170]
1. Go to the Estimation page
2. Cohort Method Evidence Explorer on the "Diagnostics" tab, the results shown have too many digits.

![image](https://user-images.githubusercontent.com/6305439/236265970-541a25c4-531b-4cb9-b6c3-276e920cd196.png)

**Comment by jreps** [comment]
This has been fixed in the most recent OhdsiShinyModules :)
