### ISSUE TITLE
Estimation --> Info Component Enhancement

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/OhdsiShinyModules#171]
1. Go to the "Estimation" screen
2. Click the "+" on the "Cohort Method Evidence Explorer" it should provide a definition and explanation for each diagnostic statistic (e.g. MDRR or EASE statistic) and also provide the cut-point / diagnostic threshold used to define categories (PASS/WARNING/FAIL)

It should also define that NA = blinded

**Comment by nhall6** [comment]
This module has changed a lot since this comment, but tooltips have been added to these column names that explain what each statistic means. NAs have also been changed to "unblind". Fixed in #issue_159 branch. Closing out
