### ISSUE TITLE
Characterization - Outcome Stratified - Type1/Type2 selection

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/OhdsiShinyModules#172]
When you make the following selection:

Type1: Outcome
Type2: Target

Results in Error in the UI (full application crash).

If you choose the same selection for both Type1 and Type2, you get a meaningless result, so we should restrict the choice of selecting the same type1 and type2 at the same time.

**Comment by jreps** [comment]
My guess is this is due to large join.  We are aiming to figure out a way to improve large data extractions, so I think this fits in with that.  Second issue could just be a warning message if both selections are the same and no data extraction?

**Comment by chrisknoll** [comment]
It crashes almost immediately, so I'm not sure it's a large join, but I am not well-versed on the codebase, so you are probably right.

**Comment by jreps** [comment]
The selection options have been updated in the shiny app and users no longer have the flexibility to run into this issue :)
