### ISSUE TITLE
Estimation --> Diagnostic vs Results Tab Present Information In Same Way

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/OhdsiShinyModules#175]
The “Diagnostics” tab and the “Results” tab within the Estimation module should both present information the same way (I.e. if you use drop-drown menus and/or radio buttons in the “Results” tab then you should do the same in the “Diagnostics” tab).  I don’t have a strong preference for whether we use drop-down menus / check boxes vs. filterable columns but the two tabs should present the results in a similar format.

Diagnostics tab is a table:
![image](https://user-images.githubusercontent.com/6305439/236275576-bf95ce5d-afa9-4f94-bad0-4a4905591410.png)

Results tab has nice filters:
![image](https://user-images.githubusercontent.com/6305439/236275668-248df8a1-e434-4c36-8ed8-e247d7a316d9.png)

**Comment by nhall6** [comment]
this has been re-organized and designed, marking as completed
