### ISSUE TITLE
Characterization - Time To Event - Plot Axis Labels

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/OhdsiShinyModules#176]
Once more than 4 databases are selected (ie 4 plots shown on a row), the plots begin to become crowded and the x-axis labels overlap. Example:

![image](https://user-images.githubusercontent.com/6818777/236276047-19dde064-71ba-4d80-9142-fa1faaad0b3a.png)

**Comment by nhall6** [comment]
Tested in a few different schemas. Behavior seems to be fixed, closing for now
