### ISSUE TITLE
Estimation --> Diagnostic Summary

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/OhdsiShinyModules#178]
We believe that the diagnostics on the Estimation screen can be improved.  Here are some ideas to improve that:

- Lets only display “PASS/FAIL/WARNING” but you can click and drill down to see the diagnostic value that led to that PASS / FAIL / WARNING.
  - Similar approach to PLP
  - Within the Estimation module, the diagnostics tab should provide an “export CSV” functionality like there is in the other Strategus tabs.
- It might help to have the “Diagnostics” tab start with a general summary that orients the user to the diagnostic performance of the study, “This study included X outcomes, Y targets, Z comparators which yielded X analysis variants. Of those analysis variants, Y passed diagnostics, explore these results in the “diagnostics” tab.
- It would be also good to know a summary of the failures and knowing how they failed.  Like X failed equipoise, etc.
- This could also be a heat map to represent the diagnostic results (greens and reds)

**Comment by nhall6** [comment]
this has also been fixed since this issue was raised
