### ISSUE TITLE
CohortMethod covariate balance bug and enhancement

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/OhdsiShinyModules#18]
1 bug, 1 suggestion for enhancement related to bug:

The covariate balance plot appears to have a rendering issue, whereby when you seek to hover over a dot, the graph jitters, moving the cursor relation to the dot, therefore not allowing the tooltip label to persist.

![image](https://user-images.githubusercontent.com/731930/188559793-30dd4fe4-b650-44ca-8ac0-9c938a10e0c5.png)

Enhancement idea:

The table underlying this graph contains covariate mean before and after adjustment for target and comparator, as well as StDiff before and after.    We should allow for user to select between viewing the graph above or exploring the table itself.   User could then sort or filter on each column (with the main use case being searching a substring in the covariate name field to find the prevalence and stdiff for a particular covariate of interest).

**Comment by jreps** [comment]
Bug has been fixed in develop.  Still need to add a table.
