### ISSUE TITLE
Toggle between databaseId, databaseName in all apps

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/OhdsiShinyModules#181]
In general we have three ways to help identify a dataSource. a) databaseId, b) databaseName, c) databaseDescription, where databaseDescription is a long paragraph like text, databaseName is a human understandable (usually the official/formal name), and databaseId serving as the short hand (sometime key) to identify. Generally databaseId is short, databaseName is long.

Most app's appear to show databaseName as default without the option of toggling to databaseId.  Many times the databaseName is long and does not fit in allocated space of the table header/plot legend - causing crowding and difficultly to interpret. 

But many times there is a legitimate need for databaseId vs databaseName. In all apps - a toggle to use databaseId vs databaseName in the UI would be useful.

**Comment by nhall6** [comment]
This has since been largely addressed. The standard way we display data sources in tables and results is through the source's abbreviation (cdmSourceAbbreviation). Under the hood, databaseId is still accessible and also can sometimes be viewed in the results themselves.
