### ISSUE TITLE
Kaplan-Meier plot rendering issues

### ISSUE THREAD

**Issue by jmb01** [OHDSI/OhdsiShinyModules#187]
Kaplan-Meier plots in the [ASE_010/011 Shiny](https://rconnect.jnj.com/ASE_010_011/) appear to render in an unhelpful way due to the long concatenated cohort names (see example below and please ignore the background/font color as I was experimenting with setting a ggplot theme at the top of my app.R).

I think the quickest fix is to just replace the cohort names with "Target" and "Comparator", which avoids dealing with these long strings. The target and comparator cohorts are identified in the plot caption anyway. 

![KaplanMeier](https://github.com/OHDSI/OhdsiShinyModules/assets/1714516/657f09c8-b9f3-47a9-abd8-87360d8ba478)

 Note that this app was created using the "standardization" branch of OhdsiShinyModules.

**Comment by jreps** [comment]
This is fixed in develop
