### ISSUE TITLE
CohortMethod Propensity score labeling

### ISSUE THREAD

**Issue by pbr6cornell** [OHDSI/OhdsiShinyModules#19]
On the PS distribution plot, the legend shows cohortID, but those numbers are not exposed elsewhere so no way to know which is target and which is comparator.

![image](https://user-images.githubusercontent.com/731930/188561199-46a69438-a9b0-4bb8-8711-84578126acdd.png)

Suggested solution:    either 1)  label legend with fixed values, red = 'Target' and blue = 'Comparator',   or, preferred, 2) label legend with variable values based on the cohort name, red = <target cohort name>,  blue = <comparator cohort name>.    Note, #2 requires ensuring no issues with length of cohort name in labeling.   (possible alternative to combine the idea, set legend to fixed values, but then print cohort names Target: <target cohort name>, Comparator: <comparator cohort name>  as text below the graph.

**Comment by jreps** [comment]
Seems this was previously fixed by Josh
