### ISSUE TITLE
Kaplan Meier Plot confidence limits should be step function 

### ISSUE THREAD

**Issue by jmb01** [OHDSI/OhdsiShinyModules#198]
![image](https://github.com/OHDSI/OhdsiShinyModules/assets/1714516/e3fa7176-74e4-40af-9954-d616a07e207f)

When a K-M plot has few events you can see that the confidence limit shading does not mirror the survival function estimate.This should be fixable by using [geom_stepribbon()](https://adibender.github.io/pammtools/reference/geom_stepribbon.html).

**Comment by jreps** [comment]
The function requires adding another dependency (pammtools) which is undesirable.  I'm looking to see whether there is a ggplot2 solution.

**Comment by jreps** [comment]
I was able to fix this used ggplot2::geom_rect() and calculating the next t, see https://github.com/OHDSI/OhdsiShinyModules/tree/issue_198
