### ISSUE TITLE
Example Shiny App does not work

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/OhdsiShinyModules#216]
The Example provided is not working:

Warning: Error in createLargeSqlQueryDt: could not find function "createLargeSqlQueryDt"

This function is not exported in OhdsiShinyModules.

Please test the example as part of the release procedure.

**Comment by jreps** [comment]
There is now an example here https://github.com/OHDSI/OhdsiShinyModules/blob/main/extras/examples/app.R and this works :)
