### ISSUE TITLE
cohortDiagnosticsSever -> cohortDiagnosticsServer

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/OhdsiShinyModules#217]
When I install the packages the function cohortDiagnosticsServer does not exist but cohortDiagnosticsSever does.

Typo to be fixed (see search for cohortDiagnosticsSever) in the package

**Comment by jreps** [comment]
Need to check whether this typo is also in ShinyAppBuilder

**Comment by jreps** [comment]
This seems to have been fixed
