### ISSUE TITLE
Reenable CI testing on ubuntu

### ISSUE THREAD

**Issue by egillax** [OHDSI/OhdsiShinyModules#221]
Some time ago linux testing was disabled in this repo because of a java error.  I've had the same error on my ubuntu laptop using any shiny app that used java. 

Now, thanks to @jreps (or the IT guy she talked to) I think we have a solution:

Increasing the java stack size seems to solve the issue:

`options(java.parameters = "-Xss3m")`

Previously ~10 tests in this repo failed on my system. But now everything passes.

I think it's important to test on linux since it's a very common OS to use for deploying shiny apps. 

I suggest adding the following env variable to the github actions file along with re-enabling linux testing:

` _JAVA_OPTIONS: -Xss3m`

**Comment by jreps** [comment]
Good idea - I'll work on this ASAP

**Comment by jreps** [comment]
updated the actions to add linux
