### ISSUE TITLE
filter by data source in custom incidence rate plots

### ISSUE THREAD

**Issue by jamieweaver** [OHDSI/OhdsiShinyModules#265]
Having an option to filter by data source in custom IR plots would be very helpful. multiple selection dropdown unavailable for data source. tagging @jhardin29
![image](https://github.com/OHDSI/OhdsiShinyModules/assets/7608016/6e8e5da2-e372-4332-b578-8b50bf1225a1)

**Comment by nhall6** [comment]
Fixed in develop. I have added a database selection filter to the results selector. This will allow the user to select which databases they want to appear in both the table and all plots.
