### ISSUE TITLE
modelDesigns not displayed when viewing model from external validation

### ISSUE THREAD

**Issue by egillax** [OHDSI/OhdsiShinyModules#275]
Get the following error:
![image](https://github.com/OHDSI/OhdsiShinyModules/assets/24678081/c0ff7542-652c-43c2-abf3-13cea92ded04)

This stems from [these](https://github.com/OHDSI/OhdsiShinyModules/blob/main/R/patient-level-prediction-modelSummary.R#L393-L400) lines in `patient-level-prediction-modelSummary.R`

```R
 modelType <- connectionHandler$queryDb(
    'select distinct model_type from 
    @schema.@plp_table_prefixmodels 
    where model_design_id = @model_design_id;',
    schema = resultDatabaseSettings$schema,
    plp_table_prefix = resultDatabaseSettings$plpTablePrefix,
    model_design_id = modelDesignId()
  )
```

This gives an empty results since the `models` table is empty for validations. I believe this can be fixed by getting the same info from the `model_settings` table which is populated for validations:

```R
  modelType <- connectionHandler$queryDb(
    'select distinct ms.model_type from 
    @schema.@plp_table_prefixmodel_settings ms
    inner join 
    @schema.@plp_table_prefixmodel_designs md
    on ms.model_setting_id = md.model_setting_id
    where md.model_design_id = @model_design_id;',
    schema = resultDatabaseSettings$schema,
    plp_table_prefix = resultDatabaseSettings$plpTablePrefix,
    model_design_id = modelDesignId()
  )
```

**Comment by nhall6** [comment]
@jreps this is from a while ago - can we close it?
