### ISSUE TITLE
select reasonable column display defaults

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/OhdsiShinyModules#290]
prevent initial horizontal scrolling in table displays (leverage sparklines where applicable instead of all distribution columns by default being displayed)

**Comment by nhall6** [comment]
@jreps - have you tried including sparklines into reactables in the past? I remember seeing some code that I think you wrote that attempted this. If I remember correctly, there was some issue preventing the sparklines from working properly inside the reactable - is that true?

**Comment by jreps** [comment]
sparklines in reactable was difficult if I remember correctly unless you have the full data (but we generally only have aggregate stuff)

**Comment by nhall6** [comment]
> sparklines in reactable was difficult if I remember correctly unless you have the full data (but we generally only have aggregate stuff)

For now I will close this then, as our column display defaults seem optimized if sparklines is not feasible given our aggregate data.
