### ISSUE TITLE
SCCS module target / indications dropdown shows negative controls

### ISSUE THREAD

**Issue by schuemie** [OHDSI/OhdsiShinyModules#292]
![image](https://github.com/OHDSI/OhdsiShinyModules/assets/6713328/2316f1fc-0fca-4086-8930-6e96b2d60dda)

Using 
```r
remotes::install_github('ohdsi/OhdsiShinyModules', ref = 'estimation-updated')
remotes::install_github("ohdsi/ShinyAppBuilder", ref = "estimation")
```
as requested by @jreps.

This is probably because we’re using negative control exposures in the vignette. Should be an easy fix: add ‘WHERE true_effect_size IS NULL’ here: https://github.com/OHDSI/OhdsiShinyModules/blob/42f5bb42c731fd9ff1a9c96bb68b624fd357ba78/R/helpers-sccsDataPulls.R#L58

Could we also have the drugs listed in alphabetical order?

A nice to have would be if the dropbox after closing shows the selected drug instead of just the indication:
 
![image](https://github.com/OHDSI/OhdsiShinyModules/assets/6713328/1e75369c-3a47-426f-b8b4-c31146d1376a)

I think @azimov has already done some work on this.

**Comment by jreps** [comment]
This is on a different branch I think?
