### ISSUE TITLE
SCCS module results currently has no drill-downs

### ISSUE THREAD

**Issue by schuemie** [OHDSI/OhdsiShinyModules#293]
There is currently no way to access the drill-downs for a result. There used to be an action button for each row that would allow you to see the Power, Attrition tabs, etc., but it is gone. Selecting a row has no effect:

![image](https://github.com/OHDSI/OhdsiShinyModules/assets/6713328/6ec7fa28-fe0e-4249-8a97-e1867a07c4cd)

Using
```r
remotes::install_github('ohdsi/OhdsiShinyModules', ref = 'estimation-updated')
remotes::install_github("ohdsi/ShinyAppBuilder", ref = "estimation")
```
as requested by @jreps.

**Comment by jreps** [comment]
I have an action button on mine?  Did you play with the selected columns?

**Comment by jreps** [comment]
fixed in the branch
