### ISSUE TITLE
Prevalence scatterplot for cohort comparisons

### ISSUE THREAD

**Issue by jamieweaver** [OHDSI/OhdsiShinyModules#294]
For comparing 1) dichotomous characteristics of one cohort by two databases, and 2) dichotomous characteristics of two cohorts within one database, having a prevalence scatterplot would be helpful for users to get a broad understanding of cohort (dis)similarity. There is an example below. This is redundant with the visualization options available in CohortDiagnostics, but for characterization analyses conditional on completed phenotypes, this information will be informative in large scale settings (i.e., many TIs, many CIs, many databases. Please label as enhancement.
![image](https://github.com/OHDSI/OhdsiShinyModules/assets/7608016/ec7b6310-8c8a-47d7-8757-0fc6202242d0)

**Comment by nhall6** [comment]
@jamieweaver I just added these (thanks for the suggestion), so marking as closed. See here: https://github.com/OHDSI/OhdsiShinyModules/pull/353
