### ISSUE TITLE
Error in "Download data" functionality in the "Inclusion Rules & Attrition" tab within the Cohorts module of a Strategus dashboard

### ISSUE THREAD

**Issue by conovermitch** [OHDSI/OhdsiShinyModules#298]
I encountered an error in multiple Strategus dashboards when attempting to use the "Download data" function inside the "Inclusion Rules and Attrition" tab of the "Cohorts" module. When I click the button, the download appears to execute in my browser but when I go to locate the downloaded file I see an error that states "cohortGeneratorDownloadAttritionTable.html - site wasn't available."  I've included a screen grab below to show the error. To be clear, the download data functions for other tabs/modules seem to be working fine. It is just this one that is misbehaving.

The dashbaord's I'm using are internal to my organization so I won't share them but I was able to reproduce this behavior across multiple Strategus dashboards (some generated by me, some generated by others). In both cases, the Strategus dashboards were generated with OhdsiShinyModules v2.1.5.9000 and ShinyAppBuilder v2.0.1.9000

Let me know if I can provide any further information to clarify the issue.

![image](https://github.com/OHDSI/OhdsiShinyModules/assets/54037718/e09d9ece-a8e3-4c36-b4eb-80dd65d7e7f3)

**Comment by nhall6** [comment]
@conovermitch - Fixed in https://github.com/OHDSI/OhdsiShinyModules/pull/332
