### ISSUE TITLE
Characterization --> Cohort Incidence --> Incidence Results: Download

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/OhdsiShinyModules#302]
Generated with OhdsiShinyModules v2.1.5.9000 and ShinyAppBuilder v2.0.1.9000

The Download (Full) downloads a file, but the "details" tab in the file is empty.

The Download (Filtered) doesn't seem to download any file.

I've noticed similar issues across other Download buttons and will continue to document when I catch it.

**Comment by nhall6** [comment]
@ericaVoss this is now fixed, and the filtered data download should actually work now for all modules: https://github.com/OHDSI/OhdsiShinyModules/pull/332
