### ISSUE TITLE
Add option for target cohort id and comparator cohort id in estimation tab

### ISSUE THREAD

**Issue by jswerdel** [OHDSI/OhdsiShinyModules#314]
I would like the option to filter by target cohort id and/or comparator cohort id in estimation tab.  Currently, the options are:
![image](https://github.com/user-attachments/assets/8c595b1c-393c-44b4-bf9b-10fdc4fe9d09)

This would allow filtering for specific cohort ids which would be very useful especially in studies with a larger number of cohorts.

**Comment by nhall6** [comment]
@jswerdel I have fixed this here: https://github.com/OHDSI/OhdsiShinyModules/pull/317/files
