### ISSUE TITLE
Covariate balance plot for CohortMethod diagonal is not diagonal

### ISSUE THREAD

**Issue by schuemie** [OHDSI/OhdsiShinyModules#315]
In the balance plot there's a dashed line that should be the diagonal, but it is not really diagonal. For example:
![image](https://github.com/user-attachments/assets/2a4ee5c6-42d3-4169-b711-1e631b2819d8)
here the line does not go through (0.05, 0.05) or (0.10, 0.10)

**Comment by nhall6** [comment]
I have fixed this here and submitted a PR @schuemie: https://github.com/OHDSI/OhdsiShinyModules/pull/316/files
