### ISSUE TITLE
Cannot "View Results" for meta/Bayesian analyses in the Cohort Method (Estimation - Results - Cohort Method Table - Power Tab)

### ISSUE THREAD

**Issue by conovermitch** [OHDSI/OhdsiShinyModules#319]
Attempting to view summary results for the meta/Bayesian analyses in the Cohort Method interface (Estimation - Results - Cohort Method Table - Power Tab) yields an error message and all of the cells that I would expect to be populated show values of either 0 or NaN (screen shot below).  This seems to be the case for any analysis I try to pull up.

The error message is as follows: "ERROR: An error has occurred. Check your logs or contact the app author for clarification."

![image](https://github.com/user-attachments/assets/555f6217-ff78-46c2-b31d-5238888a6639)

**Note**: The application I'm using deploys OhdsiShinyModules v2.1.5.9000 and ShinyAppBuilder v2.0.1.9000

**Comment by nhall6** [comment]
@conovermitch I believe this is since fixed, given that this finding was from an app from almost a year ago. But please re-open if the issue persists

**Comment by conovermitch** [comment]
Not objecting to closing this issue but note that this issue is from a recent-ish version of the app pushed by @jreps (SD Causal application).  I think it was pushed at the end of June.
