### ISSUE TITLE
Paneling in the systematic error plot 

### ISSUE THREAD

**Issue by conovermitch** [OHDSI/OhdsiShinyModules#320]
**Note**: The application I'm using deploys OhdsiShinyModules v2.0.2 and ShinyAppBuilder v2.0.0  Given that these are older versions , I'm not sure this problem still persists in updated versions of the package. If this issue has already been addressed please feel free to deprecate it. 

**Location of issue within the Strategus application**: SCCS -> Results Tab -> View Results -> Systematic Error

**Issue**: When viewing the systematic error plot, the top and bottom panels refer to "Calibrated" and "Uncalibrated" negative control distributions, respectively. However, the plot introduces left-right paneling which should not be present. The paneling typically presents the majority of the negative control distribution in the left panels which are noted with the label "True Hazard Ratio = 1" (right-panel).  The paneling then presents a few negative controls (usually only a couple) in separate panels on the right, which are noted with the label "True Hazard Ratio = NA".  As far as I can tell, this behavior does not appear to occur for the corresponding Cohort Method negative control plots (only SCCS negative control plots).

I have attached a screen grab demonstrating the behavior below: 
![image](https://github.com/user-attachments/assets/be12c4a0-974b-45b2-a07f-dda2ebc7daea)

**Comment by nhall6** [comment]
@conovermitch I too believe this has since been fixed. Am going to close for now, but please feel free to re-open if it persists in the future.

**Comment by conovermitch** [comment]
Great! Thanks for looking into it.
