### ISSUE TITLE
Incorrect time scale for calendar time plot in SCCS Shiny module

### ISSUE THREAD

**Issue by schuemie** [OHDSI/OhdsiShinyModules#330]
The Shiny module uses [this conversion function](https://github.com/OHDSI/OhdsiShinyModules/blob/5a7b6789582e9959f1105676f31ab37f877f76d7/R/helpers-sccsPlots.R#L494):
```r
convertMonthToStartDate <- function(x){
  return(as.Date(x, origin = "1950-01-01"))
}
```
Which treats `months` as days since January 1st. But the SCCS package uses [this function](https://github.com/OHDSI/SelfControlledCaseSeries/blob/c8ea06494f39064dc9d126fd08e197ba49f25b49/R/SccsDataConversion.R#L429):
```r
convertMonthToStartDate <- function(month) {
  year <- floor(month / 12)
  month <- floor(month %% 12) + 1
  return(as.Date(sprintf(
    "%s-%s-%s",
    year,
    month,
    1
  )))
}
```
Where `months` are months.

As a consequence, the x-axis of the plot is not correct.

**Comment by nhall6** [comment]
@schuemie - which module is this function found in? In the latest release of OhdsiShinyModules v3.0.0, I do not see this convertMonthToStartDate function in any of the SCCS modules. For some reason I cannot find it.

**Comment by schuemie** [comment]
[This](https://github.com/OHDSI/OhdsiShinyModules/blob/5a7b6789582e9959f1105676f31ab37f877f76d7/R/helpers-sccsPlots.R#L490-L492) is in the `main` branch. Is that not where the latest release lives?

**Comment by nhall6** [comment]
Ah, it is in a helpers module, that's why I could not find it in the sccs modules. I will look into this further.

**Comment by nhall6** [comment]
@schuemie - do you sccs results published to a study schema I can connect to to test? In the test schema I have now, there aren't any sccs results.
