### ISSUE TITLE
Cohorts Tab: No data displayed within "Cohort Counts" or "Cohort Generation" tabs

### ISSUE THREAD

**Issue by conovermitch** [OHDSI/OhdsiShinyModules#342]
In the Cohorts tab of the Strategus Shiny application, the "Cohort Counts" and "Cohort Generation" tabs does not produce a table (although the "Inclusion Rules & Attrition" tab does contain data). At the bottom of this post, I have included a screen grab of the two tabs, which should contain a table but does not. 

**Location of issue:** Cohorts module --> Cohort Counts or Cohort Generation tabs
For JNJ-internal users, this behavior can be observed in the following application: https://rconnect.jnj.com/epi1195_strategus_v2/ To be clear I have confirmed with others that their applications are exhibiting this issue as well.

**Package Versions:** Generated with OhdsiShinyModules v3.0.0 and ShinyAppBuilder v3.0.0

**Comment by nhall6** [comment]
Thanks @conovermitch , this is now fixed here https://github.com/OHDSI/OhdsiShinyModules/pull/343

There's a PR to merge this into develop.
