### ISSUE TITLE
update ResultModelManager dependancy in DESCRIPTION

### ISSUE THREAD

**Issue by egillax** [OHDSI/OhdsiShinyModules#48]
Hi @jreps ,

Would it be possible to update the dependancy in the develop branch for ResultModelManager to point to the released version instead of develop? I think ResultModelManager just had a release so the functionality you required should be in there.

The reason I'm asking is because now the PLP develop depends on OhdsiShiny develop, which depends on ResultModelManager develop, but PLP also depends on ResultModelManager released version. This causes a dependency resolution conflict in the github actions so they fail. GA doesn't know which version of ResultModelManager to install. 

With no github actions I've a hard time testing stuff :) 

Egill

**Comment by jreps** [comment]
ah, yeah, I've been meaning to make this edit but not had any time over the past week.  The shiny changes require editing the shiny app code for PLP, I think I made most of the required edits in a side branch, but I need a little time to make sure the shiny doesn't break with the edits. In summary, I'll update the OhdsiShinyModule now but the PLP develop branch may be a little broken for shiny until I finalize it.

**Comment by egillax** [comment]
Thanks that should fix it so I can run the CI.
