### ISSUE TITLE
Adding cohort diagnostics modules

### ISSUE THREAD

**Issue by azimov** [OHDSI/OhdsiShinyModules#7]
Currently, the Diagnostics Explorer app in cohort diagnostics remains in the `inst` folder of the package. We would like to migrate it to this application.

In order to do this there are number of challenges:

* A common data model for loading the connection to the database should be implemented so that multiple connections are not made for PLP/CohortDiagnostics/CohortMethod etc if possible. (this means rewriting the logic of the CohortDiagnostics modules).

* Sub modules must be refactored slightly.

* Better handling/Removal of many of the global variables

* Better/improved handling of startup/initiation of the app

* Migration of unit tests

* Removal/Alteration of undesirable required packages such as `ggiraph`

**Comment by jreps** [comment]
I think this is now completed?
